using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace Discore.Http
{
    /// <summary>
    /// Represents a message sent in a channel within Discord.
    /// </summary>
    public class DiscordMessage : DiscordIdObject
    {
        public const int MAX_CHARACTERS = 2000;

        /// <summary>
        /// Gets the id of the channel this message was sent in.
        /// </summary>
        public Snowflake ChannelId { get; }
        /// <summary>
        /// Gets the author of this message.
        /// </summary>
        public DiscordUser Author { get; }
        /// <summary>
        /// Gets the contents of this message.
        /// </summary>
        public string Content { get; }
        /// <summary>
        /// Gets the time this message was first sent.
        /// </summary>
        public DateTime Timestamp { get; }
        /// <summary>
        /// Gets the time of the last edit to this message.
        /// </summary>
        public DateTime? EditedTimestamp { get; }
        /// <summary>
        /// Gets whether or not this message was sent with the /tts command.
        /// </summary>
        public bool TextToSpeech { get; }
        /// <summary>
        /// Gets whether or not this message mentioned everyone via @everyone.
        /// </summary>
        public bool MentionEveryone { get;  }
        /// <summary>
        /// Gets a list of all user-specific mentions in this message.
        /// </summary>
        public IReadOnlyCollection<DiscordUser> Mentions { get; }
        /// <summary>
        /// Gets a list of all roles mentioned in this message.
        /// </summary>
        public IReadOnlyCollection<Snowflake> MentionedRoles { get; }
        /// <summary>
        /// Gets a table of all attachments in this message.
        /// </summary>
        public IReadOnlyCollection<DiscordAttachment> Attachments { get; }
        /// <summary>
        /// Gets a list of all embedded attachments in this message.
        /// </summary>
        public IReadOnlyCollection<DiscordEmbed> Embeds { get; }
        /// <summary>
        /// Gets a list of all reactions to this message.
        /// </summary>
        public IReadOnlyCollection<DiscordReaction> Reactions { get; }
        /// <summary>
        /// Used for validating if a message was sent.
        /// </summary>
        public Snowflake? Nonce { get; }
        /// <summary>
        /// Gets whether or not this message is pinned in the containing channel.
        /// </summary>
        public bool IsPinned { get; }
        /// <summary>
        /// Gets the id of the webhook this message was generated from,
        /// or null if this message was not generated by a webhook.
        /// </summary>
        public Snowflake? WebhookId { get; }

        public DiscordMessage(DiscordApiData data)
            : base(data)
        {
            Content         = data.GetString("content");
            Timestamp       = data.GetDateTime("timestamp").Value;
            EditedTimestamp = data.GetDateTime("edited_timestamp").Value;
            TextToSpeech    = data.GetBoolean("tts").Value;
            MentionEveryone = data.GetBoolean("mention_everyone").Value;
            Nonce           = data.GetSnowflake("nonce");
            IsPinned        = data.GetBoolean("pinned").Value;
            ChannelId       = data.GetSnowflake("channel_id").Value;
            WebhookId       = data.GetSnowflake("webhook_id");

            DiscordApiData authorData = data.Get("author"); // TODO: may be an issue if the author is a webhook.
            Author = new DiscordUser(authorData);

            // Get mentions
            IList<DiscordApiData> mentionsData = data.GetArray("mentions");
            DiscordUser[] mentions = new DiscordUser[mentionsData.Count];

            for (int i = 0; i < mentionsData.Count; i++)
                mentions[i] = new DiscordUser(mentionsData[i]);

            Mentions = new ReadOnlyCollection<DiscordUser>(mentions);

            // Get mentioned roles
            IList<DiscordApiData> mentionRolesData = data.GetArray("mention_roles");
            Snowflake[] mentionedRoles = new Snowflake[mentionRolesData.Count];

            for (int i = 0; i < mentionRolesData.Count; i++)
                mentionedRoles[i] = mentionRolesData[i].ToSnowflake().Value;

            MentionedRoles = new ReadOnlyCollection<Snowflake>(mentionedRoles);

            // Get attachments
            IList<DiscordApiData> attachmentsData = data.GetArray("attachments");
            DiscordAttachment[] attachments = new DiscordAttachment[attachmentsData.Count];

            for (int i = 0; i < attachmentsData.Count; i++)
                attachments[i] = new DiscordAttachment(attachmentsData[i]);

            Attachments = new ReadOnlyCollection<DiscordAttachment>(attachments);

            // Get embeds
            IList<DiscordApiData> embedsData = data.GetArray("embeds");
            DiscordEmbed[] embeds = new DiscordEmbed[embedsData.Count];

            for (int i = 0; i < embedsData.Count; i++)
                embeds[i] = new DiscordEmbed(embedsData[i]);

            Embeds = new ReadOnlyCollection<DiscordEmbed>(embeds);

            // Get reactions
            IList<DiscordApiData> reactionsArray = data.GetArray("reactions");
            DiscordReaction[] reactions = new DiscordReaction[reactionsArray.Count];

            for (int i = 0; i < reactionsArray.Count; i++)
                reactions[i] = new DiscordReaction(reactionsArray[i]);

            Reactions = new ReadOnlyCollection<DiscordReaction>(reactions);
        }
    }
}
