using Discore.Http;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Discore
{
    /// <summary>
    /// Represents a message sent in a channel within Discord.
    /// </summary>
    public sealed class DiscordMessage : DiscordIdEntity
    {
        public const int MAX_CHARACTERS = 2000;

        /// <summary>
        /// Gets the ID of the channel this message is in.
        /// </summary>
        public Snowflake ChannelId { get; }
        /// <summary>
        /// Gets the author of this message.
        /// </summary>
        public DiscordUser Author { get; }
        /// <summary>
        /// Gets the contents of this message.
        /// </summary>
        public string Content { get; }
        /// <summary>
        /// Gets the time this message was first sent.
        /// </summary>
        public DateTime Timestamp { get; }
        /// <summary>
        /// Gets the time of the last edit to this message.
        /// </summary>
        public DateTime? EditedTimestamp { get; }
        /// <summary>
        /// Gets whether or not this message was sent with the /tts command.
        /// </summary>
        public bool TextToSpeech { get; }
        /// <summary>
        /// Gets whether or not this message mentioned everyone via @everyone.
        /// </summary>
        public bool MentionEveryone { get; }
        /// <summary>
        /// Gets a list of all user-specific mentions in this message.
        /// </summary>
        public IReadOnlyList<DiscordUser> Mentions { get; }
        /// <summary>
        /// Gets a list of all the IDs of mentioned roles in this message.
        /// </summary>
        public IReadOnlyList<Snowflake> MentionedRoleIds { get; }
        /// <summary>
        /// Gets a list of all attachments in this message.
        /// </summary>
        public IReadOnlyList<DiscordAttachment> Attachments { get; }
        /// <summary>
        /// Gets a list of all embedded attachments in this message.
        /// </summary>
        public IReadOnlyList<DiscordEmbed> Embeds { get; }
        /// <summary>
        /// Gets a list of all reactions to this message.
        /// </summary>
        public IReadOnlyList<DiscordReaction> Reactions { get; }
        /// <summary>
        /// Used for validating if a message was sent.
        /// </summary>
        public Snowflake? Nonce { get; }
        /// <summary>
        /// Gets whether or not this message is pinned in the containing channel.
        /// </summary>
        public bool IsPinned { get; }
        /// <summary>
        /// If this message was generated by a webhook, gets the ID of that webhook.
        /// </summary>
        public Snowflake? WebhookId { get; }
        /// <summary>
        /// Gets the type of message.
        /// </summary>
        public DiscordMessageType Type { get; }

        DiscordHttpClient http;
        DiscordApiData originalData;

        internal DiscordMessage(DiscordHttpClient http, DiscordApiData data)
            : base(data)
        {
            this.http = http;

            originalData = data;

            Content         = data.GetString("content");
            Timestamp       = data.GetDateTime("timestamp").GetValueOrDefault();
            EditedTimestamp = data.GetDateTime("edited_timestamp").GetValueOrDefault();
            TextToSpeech    = data.GetBoolean("tts").GetValueOrDefault();
            MentionEveryone = data.GetBoolean("mention_everyone").GetValueOrDefault();
            Nonce           = data.GetSnowflake("nonce");
            IsPinned        = data.GetBoolean("pinned").GetValueOrDefault();
            ChannelId       = data.GetSnowflake("channel_id").GetValueOrDefault();
            WebhookId       = data.GetSnowflake("webhook_id");
            Type            = (DiscordMessageType)(data.GetInteger("type") ?? 0);

            // Get author
            DiscordApiData authorData = data.Get("author");
            if (authorData != null)
                Author = new DiscordUser(WebhookId.HasValue, authorData);

            // Get mentions
            IList<DiscordApiData> mentionsArray = data.GetArray("mentions");
            if (mentionsArray != null)
            {
                DiscordUser[] mentions = new DiscordUser[mentionsArray.Count];

                for (int i = 0; i < mentionsArray.Count; i++)
                    mentions[i] = new DiscordUser(false, mentionsArray[i]);

                Mentions = mentions;
            }

            // Get mentioned roles
            IList<DiscordApiData> mentionRolesArray = data.GetArray("mention_roles");
            if (mentionRolesArray != null)
            {
                Snowflake[] mentionedRoles = new Snowflake[mentionRolesArray.Count];

                for (int i = 0; i < mentionRolesArray.Count; i++)
                    mentionedRoles[i] = mentionRolesArray[i].ToSnowflake().Value;

                MentionedRoleIds = mentionedRoles;
            }

            // Get attachments
            IList<DiscordApiData> attachmentsArray = data.GetArray("attachments");
            if (attachmentsArray != null)
            {
                DiscordAttachment[] attachments = new DiscordAttachment[attachmentsArray.Count];

                for (int i = 0; i < attachmentsArray.Count; i++)
                    attachments[i] = new DiscordAttachment(attachmentsArray[i]);

                Attachments = attachments;
            }

            // Get embeds
            IList<DiscordApiData> embedsArray = data.GetArray("embeds");
            if (embedsArray != null)
            {
                DiscordEmbed[] embeds = new DiscordEmbed[embedsArray.Count];

                for (int i = 0; i < embedsArray.Count; i++)
                    embeds[i] = new DiscordEmbed(embedsArray[i]);

                Embeds = embeds;
            }

            // Get reactions
            IList<DiscordApiData> reactionsArray = data.GetArray("reactions");
            if (reactionsArray != null)
            {
                DiscordReaction[] reactions = new DiscordReaction[reactionsArray.Count];

                for (int i = 0; i < reactionsArray.Count; i++)
                    reactions[i] = new DiscordReaction(reactionsArray[i]);

                Reactions = reactions;
            }
        }

        /// <summary>
        /// Updates a message with a newer partial version of the same message. This is primarily used
        /// for obtaining the full message from a message update event, which only supplies the changes
        /// rather than the full message.
        /// </summary>
        /// <exception cref="ArgumentException">Thrown if the IDs of each message do not match.</exception>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="DiscordHttpApiException"></exception>
        public static DiscordMessage Update(DiscordMessage message, DiscordMessage withPartial)
        {
            if (message == null)
                throw new ArgumentNullException(nameof(message));
            if (withPartial == null)
                throw new ArgumentNullException(nameof(withPartial));

            if (message.Id != withPartial.Id)
                throw new ArgumentException("Cannot update one message with another. The message IDs must match.");

            DiscordApiData updatedData = message.originalData.Clone();
            updatedData.OverwriteUpdate(withPartial.originalData);

            return new DiscordMessage(message.http, updatedData);
        }

        /// <summary>
        /// Adds a reaction to this message.
        /// <para>Requires <see cref="DiscordPermission.ReadMessageHistory"/>.</para>
        /// <para>Requires <see cref="DiscordPermission.AddReactions"/> if nobody else has reacted to the message prior.</para>
        /// </summary>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="DiscordHttpApiException"></exception>
        public Task CreateReaction(DiscordReactionEmoji emoji)
        {
            return http.CreateReaction(ChannelId, Id, emoji);
        }

        /// <summary>
        /// Removes a reaction from this message added from the current bot.
        /// </summary>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="DiscordHttpApiException"></exception>
        public Task DeleteOwnReaction(DiscordReactionEmoji reactionEmoji)
        {
            return http.DeleteOwnReaction(ChannelId, Id, reactionEmoji);
        }

        /// <summary>
        /// Removes a reaction from this message.
        /// <para>Requires <see cref="DiscordPermission.ManageMessages"/>.</para>
        /// </summary>
        /// <param name="user">The user who added the reacted.</param>
        /// <param name="reactionEmoji"></param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="DiscordHttpApiException"></exception>
        public Task DeleteUserReaction(DiscordUser user, DiscordReactionEmoji reactionEmoji)
        {
            if (user == null)
                throw new ArgumentNullException(nameof(user));

            return http.DeleteUserReaction(ChannelId, Id, user.Id, reactionEmoji);
        }

        /// <summary>
        /// Removes a reaction from this message.
        /// <para>Requires <see cref="DiscordPermission.ManageMessages"/>.</para>
        /// </summary>
        /// <param name="userId">The ID of the user who added the reacted.</param>
        /// <param name="reactionEmoji"></param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="DiscordHttpApiException"></exception>
        public Task DeleteUserReaction(Snowflake userId, DiscordReactionEmoji reactionEmoji)
        {
            return http.DeleteUserReaction(ChannelId, Id, userId, reactionEmoji);
        }

        /// <summary>
        /// Gets all users who reacted with the specified emoji to this message.
        /// </summary>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="DiscordHttpApiException"></exception>
        public Task<IReadOnlyList<DiscordUser>> GetReactions(DiscordReactionEmoji reactionEmoji)
        {
            return http.GetReactions(ChannelId, Id, reactionEmoji);
        }

        /// <summary>
        /// Deletes all reactions to this message.
        /// <para>Requires <see cref="DiscordPermission.ManageMessages"/>.</para>
        /// </summary>
        /// <exception cref="DiscordHttpApiException"></exception>
        public Task DeleteAllReactions()
        {
            return http.DeleteAllReactions(ChannelId, Id);
        }

        /// <summary>
        /// Pins this message to the channel it was sent in.
        /// <para>Requires <see cref="DiscordPermission.ManageMessages"/>.</para>
        /// </summary>
        /// <exception cref="DiscordHttpApiException"></exception>
        public Task Pin()
        {
            return http.AddPinnedChannelMessage(ChannelId, Id);
        }

        /// <summary>
        /// Unpins this message from the channel it was sent in.
        /// <para>Requires <see cref="DiscordPermission.ManageMessages"/>.</para>
        /// </summary>
        /// <exception cref="DiscordHttpApiException"></exception>
        public Task Unpin()
        {
            return http.DeletePinnedChannelMessage(ChannelId, Id);
        }

        /// <summary>
        /// Changes the contents of this message.
        /// <para>Note: only messages created by the current bot can be editted.</para>
        /// </summary>
        /// <returns>Returns the editted message.</returns>
        /// <exception cref="DiscordHttpApiException"></exception>
        public Task<DiscordMessage> Edit(string newContent)
        {
            return http.EditMessage(ChannelId, Id, newContent);
        }

        /// <summary>
        /// Changes the contents of this message.
        /// <para>Note: only messages created by the current bot can be editted.</para>
        /// </summary>
        /// <returns>Returns the editted message.</returns>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="DiscordHttpApiException"></exception>
        public Task<DiscordMessage> Edit(EditMessageOptions options)
        {
            return http.EditMessage(ChannelId, Id, options);
        }

        /// <summary>
        /// Deletes this message.
        /// <para>Requires <see cref="DiscordPermission.ManageMessages"/>.</para>
        /// </summary>
        /// <exception cref="DiscordHttpApiException"></exception>
        public Task Delete()
        {
            return http.DeleteMessage(ChannelId, Id);
        }
    }
}
